databaseChangeLog:
  - changeSet:
      id: 003-add-idempotency-table
      author: lmo
      changes:
        - createTable:
            tableName: idempotency_keys
            columns:
              - column:
                  name: key
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: created_at
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
