databaseChangeLog:
  - changeSet:
      id: 004-add-shedlock-table
      author: lmo
      changes:
        - createTable:
            tableName: shedlock
            columns:
              - column:
                  name: name
                  type: VARCHAR(64)
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: lock_until
                  type: TIMESTAMP WITH TIME ZONE
                  constraints:
                    nullable: false

              - column:
                  name: locked_at
                  type: TIMESTAMP WITH TIME ZONE
                  constraints:
                    nullable: false

              - column:
                  name: locked_by
                  type: VARCHAR(255)
                  constraints:
                    nullable: false

